stages:
  - package

make_rpm:
  stage: package
  only:
    - /^\d+\.\d+\.\d+$/
  script:
    - ./make_package rpm ${CI_BUILD_TAG} /repos/centos/internal/
    - createrepo /repos/centos/internal/

# No point doing this right now (if ever)
#make_deb:
#  stage: package
#  only:
#    - /^\d+\.\d+\.\d+$/
#  script:
#    - ./make_package deb ${CI_BUILD_TAG}
