make_rpm:
  script:
    - virtualenv -p python2 slack_inviter/venv
    - . slack_inviter/venv/bin/activate
    - pip install -r requirements.txt
    - deactivate
    - fpm -f -s dir -t rpm -a noarch -n slack-inviter -v 1.0.0 -p /home/packages slack_inviter=/home/app slack_inviter.conf=/etc/nginx/application.d/slack_inviter.conf

make_deb:
  script:
    - virtualenv -p python2 slack_inviter/venv
    - . slack_inviter/venv/bin/activate
    - pip install -r requirements.txt
    - deactivate
    - fpm -f -s dir -t deb -a noarch -n slack-inviter -v 1.0.0 -p /home/packages slack_inviter=/home/app slack_inviter.conf=/etc/nginx/application.d/slack_inviter.conf
